# Site settings
title: thought_stream.txt
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/blog"
url: "http://chrisjang.com"
twitter_username: wtfridge_
github_username:  cjang5
facebook_username:  

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
